<template>
  <div class="invoice-page">
    <!-- ========== PAGE HEADER ========== -->
    <div class="page-header">
      <div class="header-left">
        <h1 class="page-title">
          <span class="title-icon">🧾</span>
          Smart Payment Invoices
        </h1>
        <p class="page-subtitle">All generated invoices from payment transactions</p>
      </div>
      <div class="header-right">
        <button class="refresh-btn" @click="loadInvoices(currentPage)" :disabled="loading">
          <span :class="{ spinning: loading }">⟳</span>
          {{ loading ? 'Loading...' : 'Refresh' }}
        </button>
      </div>
    </div>

    <!-- ========== FILTERS ========== -->
    <div class="filters-card">
      <div class="filter-group">
        <label>Search</label>
        <div class="search-wrap">
          <span class="search-icon">🔍</span>
          <input
            v-model="search"
            type="text"
            placeholder="Search by invoice no, student name..."
            class="search-input"
            @input="debouncedSearch"
          />
        </div>
      </div>
      <div class="filter-group">
        <label>Invoice Type</label>
        <select v-model="filterType" class="filter-select" @change="loadInvoices(1)">
          <option value="">All Types</option>
          <option value="fee">Fee</option>
          <option value="payment">Payment</option>
          <option value="refund">Refund</option>
        </select>
      </div>
      <div class="filter-group">
        <label>Payment Method</label>
        <select v-model="filterMethod" class="filter-select" @change="loadInvoices(1)">
          <option value="">All Methods</option>
          <option value="cash">Cash</option>
          <option value="bkash">bKash</option>
          <option value="nagad">Nagad</option>
          <option value="rocket">Rocket</option>
          <option value="bank">Bank</option>
          <option value="card">Card</option>
        </select>
      </div>
    </div>

    <!-- ========== LOADING ========== -->
    <div v-if="loading" class="loading-card">
      <div class="loader-dots">
        <span></span><span></span><span></span>
      </div>
      <p>Loading invoices...</p>
    </div>

    <!-- ========== EMPTY ========== -->
    <div v-else-if="invoices.length === 0" class="empty-card">
      <div class="empty-icon">📄</div>
      <h3>No Invoices Found</h3>
      <p>No invoices match your criteria. Try adjusting filters.</p>
    </div>

    <!-- ========== TABLE ========== -->
    <div v-else class="table-card">
      <div class="table-header">
        <span class="table-count">{{ totalRecords }} invoices found</span>
      </div>

      <div class="table-wrapper">
        <table class="invoice-table">
          <thead>
            <tr>
              <th @click="toggleSort('invoice_no')" class="sortable">
                Invoice No
                <span class="sort-arrow" v-if="sortField === 'invoice_no'">{{ sortOrder === 1 ? '↑' : '↓' }}</span>
              </th>
              <th>Transaction No</th>
              <th>Student</th>
              <th @click="toggleSort('amount')" class="sortable">
                Amount
                <span class="sort-arrow" v-if="sortField === 'amount'">{{ sortOrder === 1 ? '↑' : '↓' }}</span>
              </th>
              <th>Method</th>
              <th>Period</th>
              <th>Type</th>
              <th>Generated By</th>
              <th @click="toggleSort('generated_at')" class="sortable">
                Generated At
                <span class="sort-arrow" v-if="sortField === 'generated_at'">{{ sortOrder === 1 ? '↑' : '↓' }}</span>
              </th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="inv in invoices" :key="inv.id">
              <td>
                <span class="invoice-no">{{ inv.invoice_no }}</span>
              </td>
              <td>
                <span class="trx-no">{{ inv.payment_transaction?.transaction_no || '—' }}</span>
              </td>
              <td>
                <div class="student-cell">
                  <div class="student-avatar">
                    {{ getInitial(inv) }}
                  </div>
                  <span>{{ getStudentName(inv.payment_transaction?.enrollment?.student) }}</span>
                </div>
              </td>
              <td>
                <span class="amount">৳{{ formatNumber(inv.payment_transaction?.amount || 0) }}</span>
              </td>
              <td>
                <span class="method-badge" :class="'method-' + (inv.payment_transaction?.payment_method || 'cash')">
                  {{ getMethodLabel(inv.payment_transaction?.payment_method) }}
                </span>
              </td>
              <td>
                <span class="period-text" :title="inv.metadata?.period_description || ''">
                  {{ inv.metadata?.period_description || '—' }}
                </span>
              </td>
              <td>
                <span class="type-badge" :class="'type-' + (inv.invoice_type || 'fee')">
                  {{ inv.invoice_type || 'Fee' }}
                </span>
              </td>
              <td>
                <span class="generator">{{ inv.generator?.name || 'System' }}</span>
              </td>
              <td>
                <span class="date-text">{{ formatDate(inv.generated_at) }}</span>
              </td>
              <td>
                <button class="download-btn" @click="downloadInvoice(inv)" title="Download PDF">
                  <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" width="16" height="16">
                    <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/>
                    <polyline points="7 10 12 15 17 10"/>
                    <line x1="12" y1="15" x2="12" y2="3"/>
                  </svg>
                  PDF
                </button>
              </td>
            </tr>
          </tbody>
        </table>
      </div>

      <!-- Pagination -->
      <div class="pagination" v-if="totalPages > 1">
        <button
          class="page-btn"
          :disabled="currentPage === 1"
          @click="changePage(currentPage - 1)"
        >
          ← Previous
        </button>
        
        <div class="page-numbers">
          <button
            v-for="p in visiblePages"
            :key="p"
            class="page-num"
            :class="{ active: p === currentPage }"
            @click="changePage(p)"
          >
            {{ p }}
          </button>
        </div>

        <button
          class="page-btn"
          :disabled="currentPage === totalPages"
          @click="changePage(currentPage + 1)"
        >
          Next →
        </button>
      </div>
    </div>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import smartFeeService from '@/services/smart-fee.service'

// ========== State ==========
const invoices = ref([])
const totalRecords = ref(0)
const loading = ref(false)
const currentPage = ref(1)
const perPage = 15
const sortField = ref('generated_at')
const sortOrder = ref(-1)
const search = ref('')
const filterType = ref('')
const filterMethod = ref('')
let searchTimeout = null

// ========== Computed ==========
const totalPages = computed(() => Math.ceil(totalRecords.value / perPage))

const visiblePages = computed(() => {
  const pages = []
  const max = Math.min(totalPages.value, 7)
  let start = Math.max(1, currentPage.value - 3)
  let end = Math.min(totalPages.value, start + max - 1)
  
  if (end - start + 1 < max) {
    start = Math.max(1, end - max + 1)
  }
  
  for (let i = start; i <= end; i++) {
    pages.push(i)
  }
  return pages
})

// ========== Methods ==========
const getInitial = (inv) => {
  const name = getStudentName(inv.payment_transaction?.enrollment?.student)
  return name ? name.charAt(0).toUpperCase() : '?'
}

const getStudentName = (student) => {
  if (!student) return 'N/A'
  return student.full_name || `${student.first_name || ''} ${student.last_name || ''}`.trim() || 'N/A'
}

const getMethodLabel = (method) => {
  const labels = { cash: 'Cash', bkash: 'bKash', nagad: 'Nagad', rocket: 'Rocket', bank: 'Bank', card: 'Card', check: 'Cheque' }
  return labels[method] || method || 'N/A'
}

const formatNumber = (num) => Number(num || 0).toLocaleString('en-BD')

const formatDate = (date) => {
  if (!date) return '—'
  return new Date(date).toLocaleDateString('en-BD', {
    year: 'numeric', month: 'short', day: 'numeric',
    hour: '2-digit', minute: '2-digit'
  })
}

const loadInvoices = async (page = 1) => {
  loading.value = true
  try {
    const params = {
      page,
      per_page: perPage,
      sort_field: sortField.value,
      sort_order: sortOrder.value,
    }
    if (search.value) params.search = search.value
    if (filterType.value) params.invoice_type = filterType.value
    if (filterMethod.value) params.payment_method = filterMethod.value

    const { data } = await smartFeeService.admin.invoices(params)
    invoices.value = data.data?.data || data.data || []
    totalRecords.value = data.data?.meta?.total || data.meta?.total || 0
    currentPage.value = page
  } catch (err) {
    console.error('Failed to load invoices:', err)
  } finally {
    loading.value = false
  }
}

const toggleSort = (field) => {
  if (sortField.value === field) {
    sortOrder.value = sortOrder.value === 1 ? -1 : 1
  } else {
    sortField.value = field
    sortOrder.value = -1
  }
  loadInvoices(currentPage.value)
}

const changePage = (page) => {
  if (page >= 1 && page <= totalPages.value) {
    loadInvoices(page)
    window.scrollTo({ top: 0, behavior: 'smooth' })
  }
}

const debouncedSearch = () => {
  clearTimeout(searchTimeout)
  searchTimeout = setTimeout(() => {
    loadInvoices(1)
  }, 400)
}

const downloadInvoice = async (invoice) => {
  try {
    const response = await smartFeeService.invoices.download(invoice.id)
    const url = window.URL.createObjectURL(new Blob([response.data]))
    const link = document.createElement('a')
    link.href = url
    link.setAttribute('download', `${invoice.invoice_no}.pdf`)
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
    window.URL.revokeObjectURL(url)
  } catch (err) {
    alert('Failed to download invoice')
  }
}

// ========== Lifecycle ==========
onMounted(() => loadInvoices())
</script>

<style scoped>
/* ========== CONTAINER ========== */
.invoice-page {
  padding: 1.5rem 2rem;
  max-width: 1300px;
  margin: 0 auto;
  font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
}

/* ========== PAGE HEADER ========== */
.page-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  margin-bottom: 1.5rem;
  flex-wrap: wrap;
  gap: 1rem;
}

.page-title {
  font-size: 1.5rem;
  font-weight: 700;
  color: var(--text-primary);
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin: 0;
}

.page-subtitle {
  color: var(--text-muted);
  font-size: 0.875rem;
  margin: 0.25rem 0 0;
}

.refresh-btn {
  display: inline-flex;
  align-items: center;
  gap: 0.4rem;
  padding: 0.6rem 1.25rem;
  background: var(--bg-card);
  border: 1px solid var(--border-color);
  border-radius: 0.5rem;
  font-size: 0.85rem;
  font-weight: 500;
  color: var(--text-secondary);
  cursor: pointer;
  transition: all 0.2s;
}

.refresh-btn:hover { background: var(--bg-surface-muted); border-color: #cbd5e1; }
.refresh-btn:disabled { opacity: 0.6; cursor: not-allowed; }

.spinning { animation: spin 0.8s linear infinite; display: inline-block; }
@keyframes spin { to { transform: rotate(360deg); } }

/* ========== FILTERS ========== */
.filters-card {
  display: flex;
  gap: 1rem;
  padding: 1rem 1.25rem;
  background: var(--bg-card);
  border: 1px solid var(--border-color);
  border-radius: 0.75rem;
  margin-bottom: 1.25rem;
  flex-wrap: wrap;
  align-items: flex-end;
}

.filter-group {
  display: flex;
  flex-direction: column;
  gap: 0.3rem;
  flex: 1;
  min-width: 180px;
}

.period-text { font-size: 0.8rem; color: var(--text-muted); max-width: 140px; display: inline-block; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.filter-group label {
  font-size: 0.7rem;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.5px;
}

.search-wrap {
  display: flex;
  align-items: center;
  border: 1px solid var(--border-color);
  border-radius: 0.5rem;
  overflow: hidden;
  background: var(--bg-card);
}

.search-wrap:focus-within {
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59,130,246,0.1);
}

.search-icon {
  padding: 0 0.75rem;
  font-size: 0.85rem;
}

.search-input {
  flex: 1;
  padding: 0.6rem 0.5rem 0.6rem 0;
  border: none;
  outline: none;
  font-size: 0.85rem;
}

.filter-select {
  padding: 0.6rem 0.75rem;
  border: 1px solid var(--border-color);
  border-radius: 0.5rem;
  font-size: 0.85rem;
  outline: none;
  background: var(--bg-card);
  cursor: pointer;
}

.filter-select:focus {
  border-color: #3b82f6;
  box-shadow: 0 0 0 3px rgba(59,130,246,0.1);
}

/* ========== LOADING & EMPTY ========== */
.loading-card, .empty-card {
  text-align: center;
  padding: 3rem 2rem;
  background: var(--bg-card);
  border: 1px solid var(--border-color);
  border-radius: 0.75rem;
}

.loader-dots {
  display: flex;
  justify-content: center;
  gap: 6px;
  margin-bottom: 1rem;
}

.loader-dots span {
  width: 10px;
  height: 10px;
  border-radius: 50%;
  background: #3b82f6;
  animation: bounce 1.4s infinite ease-in-out;
}

.loader-dots span:nth-child(1) { animation-delay: 0s; }
.loader-dots span:nth-child(2) { animation-delay: 0.16s; }
.loader-dots span:nth-child(3) { animation-delay: 0.32s; }

@keyframes bounce {
  0%, 80%, 100% { transform: scale(0.3); }
  40% { transform: scale(1); }
}

.loading-card p { color: var(--text-muted); }

.empty-icon { font-size: 2.5rem; margin-bottom: 0.5rem; }
.empty-card h3 { color: var(--text-primary); margin: 0.5rem 0; }
.empty-card p { color: var(--text-muted); margin: 0; }

/* ========== TABLE CARD ========== */
.table-card {
  background: var(--bg-card);
  border: 1px solid var(--border-color);
  border-radius: 0.75rem;
  overflow: hidden;
}

.table-header {
  padding: 1rem 1.25rem;
  border-bottom: 1px solid var(--border-color);
}

.table-count {
  font-size: 0.8rem;
  color: var(--text-muted);
  font-weight: 500;
}

.table-wrapper {
  overflow-x: auto;
}

/* ========== TABLE ========== */
.invoice-table {
  width: 100%;
  border-collapse: collapse;
}

.invoice-table thead th {
  background: var(--bg-surface-muted);
  padding: 0.85rem 1rem;
  text-align: left;
  font-size: 0.72rem;
  font-weight: 600;
  color: var(--text-muted);
  text-transform: uppercase;
  letter-spacing: 0.5px;
  border-bottom: 2px solid #e2e8f0;
  white-space: nowrap;
}

.sortable {
  cursor: pointer;
  user-select: none;
}

.sortable:hover {
  color: var(--text-primary);
}

.sort-arrow {
  margin-left: 0.25rem;
  font-size: 0.7rem;
}

.invoice-table tbody td {
  padding: 0.85rem 1rem;
  border-bottom: 1px solid var(--border-light);
  font-size: 0.85rem;
  color: var(--text-secondary);
}

.invoice-table tbody tr:hover {
  background: var(--bg-surface-muted);
}

/* ========== CELL STYLES ========== */
.invoice-no {
  font-family: 'SF Mono', 'Fira Code', monospace;
  font-weight: 600;
  color: #3b82f6;
  background: #eff6ff;
  padding: 0.2rem 0.5rem;
  border-radius: 4px;
  font-size: 0.8rem;
}

.trx-no {
  font-family: 'SF Mono', monospace;
  font-size: 0.78rem;
  color: var(--text-muted);
}

.student-cell {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.student-avatar {
  width: 2rem;
  height: 2rem;
  border-radius: 50%;
  background: #6366f1;
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 0.7rem;
  font-weight: 600;
  flex-shrink: 0;
}

.amount {
  font-weight: 600;
  color: var(--text-primary);
}

.method-badge {
  display: inline-block;
  padding: 0.2rem 0.6rem;
  border-radius: 6px;
  font-size: 0.72rem;
  font-weight: 600;
}

.method-cash { background: #dbeafe; color: #2563eb; }
.method-bkash { background: #fce7f3; color: #be185d; }
.method-nagad { background: #d1fae5; color: #059669; }
.method-rocket { background: #fef3c7; color: #d97706; }
.method-bank { background: #e0e7ff; color: #4338ca; }
.method-card { background: #f3e8ff; color: #7c3aed; }
.method-check { background: #e2e8f0; color: var(--text-secondary); }

.type-badge {
  display: inline-block;
  padding: 0.2rem 0.6rem;
  border-radius: 6px;
  font-size: 0.72rem;
  font-weight: 600;
  text-transform: capitalize;
}

.type-fee { background: #dbeafe; color: #2563eb; }
.type-payment { background: #d1fae5; color: #059669; }
.type-refund { background: #fef3c7; color: #d97706; }

.generator {
  font-size: 0.8rem;
  color: var(--text-muted);
}

.date-text {
  font-size: 0.8rem;
  color: var(--text-muted);
  white-space: nowrap;
}

.download-btn {
  display: inline-flex;
  align-items: center;
  gap: 0.35rem;
  padding: 0.35rem 0.75rem;
  background: #eff6ff;
  color: #3b82f6;
  border: none;
  border-radius: 0.4rem;
  font-size: 0.78rem;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.15s;
}

.download-btn:hover {
  background: #dbeafe;
}

/* ========== PAGINATION ========== */
.pagination {
  display: flex;
  justify-content: center;
  align-items: center;
  gap: 0.5rem;
  padding: 1rem;
  border-top: 1px solid #e2e8f0;
}

.page-btn {
  padding: 0.45rem 0.85rem;
  border: 1px solid var(--border-color);
  background: var(--bg-card);
  border-radius: 0.4rem;
  font-size: 0.8rem;
  cursor: pointer;
  transition: all 0.15s;
}

.page-btn:hover { background: var(--bg-surface-muted); }
.page-btn:disabled { opacity: 0.4; cursor: not-allowed; }

.page-numbers {
  display: flex;
  gap: 0.25rem;
}

.page-num {
  width: 2rem;
  height: 2rem;
  display: flex;
  align-items: center;
  justify-content: center;
  border: 1px solid var(--border-color);
  background: var(--bg-card);
  border-radius: 0.4rem;
  font-size: 0.8rem;
  cursor: pointer;
  transition: all 0.15s;
}

.page-num:hover { background: var(--bg-surface-muted); }

.page-num.active {
  background: #3b82f6;
  color: white;
  border-color: #3b82f6;
}

/* ========== RESPONSIVE ========== */
@media (max-width: 768px) {
  .invoice-page { padding: 1rem; }
  .filters-card { flex-direction: column; }
  .filter-group { min-width: 100%; }
}
</style>