/**
 * Default permissions per role when explicit DB permissions are missing.
 * Keeps sidebar visibility and router guards in sync.
 */
export const roleDefaultPermissions = {
  admin: [
    'view users', 'view roles', 'view permissions',
    'view students', 'view guardians', 'view admissions',
    'view academic sessions', 'view classes', 'view sections', 'view subjects', 'view academic groups', 'view class routines', 'view routine exceptions',
    'view courses', 'view batches', 'view enrollments', 'create courses', 'create batches', 'create enrollments', 'edit courses', 'edit batches',
    'view attendance',
    'view student attendance', 'view teacher attendance', 'view employee attendance',
    'view attendance sessions', 'view biometric devices',
    'view attendance reports', 'view attendance dashboard', 'view device simulator',
    'view exams', 'view exam types', 'view exam routines', 'view exam results',
    'view fee types', 'view fee structures', 'view fee collections', 'view expenses',
    'view employees', 'view departments', 'view designations', 'view staff attendance', 'view leave requests', 'view payroll',
    'view notice board', 'view notifications',
    'view cms pages', 'view sliders', 'view events', 'view gallery', 'view testimonials',
    'view success stories', 'view study materials', 'view download center',
    'approve cms content', 'approve notice board', 'view cms audit logs', 'view cms analytics',
    'view reports', 'view settings',
  ],
  teacher: [
    'view teachers',
    'view classes', 'view sections', 'view subjects',
    'view students',
    'view attendance',
    'view student attendance', 'view teacher attendance',
    'view attendance reports',
    'view exams', 'view exam types', 'view exam routines', 'view exam results',
    'create exam results', 'edit exam results',
    'view notice board', 'view notifications',
    'view my schedule',
    'view study materials', 'create study materials', 'edit study materials',
  ],
  student: [
    'view attendance',
    'view exams', 'view exam results', 'view exam routines',
    'view classes', 'view subjects', 'view class routines',
    'view fee collections',
    'view notice board',
    'view study materials',
    'view download center',
  ],
  employee: [
    'view attendance',
    'view employees', 'view departments', 'view designations',
    'view staff attendance', 'create staff attendance',
    'view leave requests', 'create leave requests', 'view leave types',
    'view payroll',
    'view notice board', 'view notifications',
    'view events', 'view gallery',
    'view download center',
  ],
  guardian: [
    'view students',
    'view attendance',
    'view exams', 'view exam results',
    'view fee collections',
    'view notice board',
    'view download center',
  ],
}
